version: "2"

services:
  bot:
    image: node:13.1.0-alpine3.10
    container_name: bot
    volumes:
      - ./:/bot
      - /var/run/docker.sock:/docker.sock
    working_dir: /bot
    command: ["node", "index.js"]