version: "2.2"

services:
  bot:
    image: node:13.1.0-alpine3.10
    container_name: bot
    ports: 
      - 3000:3000
    volumes:
      - ./:/bot
      - /var/run/docker.sock:/docker.sock
    working_dir: /bot
    command: ["node", "index.js"]